### ISSUE TITLE
DLR not forwarded back to smpp client

### ISSUE THREAD

**Issue by Eudorajab1** [jookies/jasmin#418] opened 2016-04-14 23:11 UTC
Hi All,
Whilst doing some integration testing I have noticed the following :-
1: dlr with smtp msgid id SAR-2347039245475-1EEDF843-2-1 is not forwarded to smtp bound client
even though the dlr is received in messages.log with no issues
2: :SMSC_DELIVERY_RECEIPT_REQUESTED
Has anyone experienced similar issues with SAR ? 

Here's a log snapshot:

    2016-04-14 23:25:58 INFO     926 SMS-MT [cid:X] [queue-msgid:c0114943-4470-4813-ad5a-b0dc29d07a8b] [smpp-msgid:SAR-2347039245475-1eedf843-2-1] [status:ESME_ROK] [prio:0] [dlr:SMSC_DELIVERY_RECEIPT_REQUESTED]
    2016-04-14 23:26:01 INFO     926 DLR [cid:X] [smpp-msgid:SAR-2347039245475-1EEDF843-2-1] [status:UNDELIV]

**Comment by KumarDedhia** [comment] 2016-04-15 05:15
Is this case for every msg??

**Comment by Eudorajab1** [comment] 2016-04-15 09:42
I havent had time to check every single message but it seems to be looking at the overall stats.

**Comment by farirat** [comment] 2016-04-16 09:31
@KumarDedhia, no this is not a general issue, it will get high prio otherwise, the issue's discovered by @Eudorajab1 and i think it's related to the smpp-msgid format: **SAR-2347039245475-1EEDF843-2-1**.

I need to reproduce the issue with the same smpp-msgid to confirm this issue.

**Comment by Eudorajab1** [comment] 2016-04-16 19:04
It is definately only on the SAR messaes

**Comment by farirat** [comment] 2016-04-16 19:45
@Eudorajab1 what do you mean by "SAR" message ?

**Comment by Eudorajab1** [comment] 2016-04-17 08:09
Sorry .. I mean it is an issue with the particular DLR SAR format. All other DLR’s seem to be forwarded as they should.

**Comment by farirat** [comment] 2016-04-23 23:06
unreproducable issue, and even after investigation on production env, jasmin seems to be handling these dlr the right way, closing issue as 'invalid'

**Closed by farirat** 2016-04-23 23:06 UTC
Labels: bug, discussion
