### ISSUE TITLE
SMPP DLR not sent

### ISSUE THREAD

**Issue by astutesoftware** [jookies/jasmin#405] opened 2016-03-16 03:08 UTC
On a standard installation with a standard user and connection (with basic information), 
the sms is being delivered but the client who sends the sms over smpp does not receive a DLR from jasmin.

Upon further inspection we find that the KEYS are being stored in a different CASE in redis than what jasmin has in memory. Probably this causes it not to find the appropriate keys.

user dlr_level is default (1).
and dlr_msgid is kept default.

**Comment by farirat** [comment] 2016-03-16 11:57
Which Jasmin version are you using ?

**Comment by KumarDedhia** [comment] 2016-03-18 10:23
Even i m facing the same issue.
I am using v0.9b0.
I found this error.
Thanks in advance.
![screenshot from 2016-03-18 15-36-23](https://cloud.githubusercontent.com/assets/17925214/13875010/4edc8432-ed21-11e5-84e4-e9d798330469.png)

**Comment by KumarDedhia** [comment] 2016-03-18 10:40
Even i am facing the same issue,
I m using v0.9b0
I found error in syslog.
![err](https://cloud.githubusercontent.com/assets/17925214/13875429/d29634ba-ed23-11e5-80e0-e920afd60f4f.PNG)

**Comment by farirat** [comment] 2016-03-19 11:27
Same issue is in 0.9b1 ?

**Comment by farirat** [comment] 2016-03-19 12:47
Issue reproduced in 0.9b0 and b1.

**Comment by farirat** [comment] 2016-03-19 21:44
Issue fixed, please upgrade to 0.9b2

**Comment by KumarDedhia** [comment] 2016-03-21 07:05
I have upgraded to v0.9b2.
but found the same error when requesting for dlr in case of smpp

**Comment by farirat** [comment] 2016-03-21 08:35
Can you please provide:

1. the steps to reproduce the issue,
2. the sms parameters (source/destination/content ...), a pdu dump will be helpful,
3. printscreen (again) of the error

**Comment by KumarDedhia** [comment] 2016-03-21 09:23
This issue is not seen when dlr is not requested.

messages.log
![messages log](https://cloud.githubusercontent.com/assets/17925214/13914438/5ebefad8-ef74-11e5-8284-2dda374d0f79.png)

default-smpps_01.log
![smpps_01 log](https://cloud.githubusercontent.com/assets/17925214/13914439/5ecd2202-ef74-11e5-8e47-72a58c7922a6.png)

error in syslog
![syslog log](https://cloud.githubusercontent.com/assets/17925214/13914440/5ed54e0a-ef74-11e5-9379-6c7420b979dc.png)

**Comment by KumarDedhia** [comment] 2016-03-21 09:28
Also DLR is not mapped properly, and thrown with different Connector.
The line says:-- ##** code_dlr_msgid: 21015 coded is to 21015 instead of 5217(as found in redis).**
connector's dlr_msgid in jcli is set to 0

**Comment by farirat** [comment] 2016-03-21 22:36
I tried to reproduce your issue to get:

    struct.error: 'L' format requires

But with no success, is it possible to provide access to test node ? with possibility to reproduce the issue anytime ? if yes then please send credentials to support@jasminsms.com

As for the dlr coding, it's a separate issue, i've created #408 to track it in next minor version (0.9b3), but anyway, even if there were no issue with the leading zeroes in the msgid, your dlr_msgid must be 1 instead of 0 because i can see 21015=0x5217 (the first is the deliver_sm while the second is the submit_sm_resp).

Another point, your dlr seems to be coming from a different connector than the one used to send the sms, is it something you're doing intentionally ?

**Comment by KumarDedhia** [comment] 2016-03-22 05:49
I changed the working env, purged the apt-get installation and running the script directly,
now it seems to work without that issue.
Dlr from different connector might be, bcoz both the connectors are bound to same virtual SMSC for testing.
I am planning to change SMSC and give a try for dlr_msgid=1.
Thanks

**Comment by farirat** [comment] 2016-03-22 08:34
Great !

So going to re-close this issue and keep the #408 going.

**Closed by farirat** 2016-03-22 08:34 UTC
Labels: bug, critical
