### ISSUE TITLE
Trouble with adding Filter ro Router

### ISSUE THREAD

**Issue by xamaxmacko** [jookies/jasmin#194] opened 2015-06-19 15:13 UTC
Hello community.

I've faced the proble with creating multiple routes.

I've created SourceAddrFilter and tried to set it to a StaticMTRoute.

The result is here:

jcli : mtrouter -a
Adding a new MT Route: (ok: save, ko: exit)
> type StaticMTRoute
jasmin.routing.Routes.StaticMTRoute arguments:
filters, connector, rate
> filters test
SourceAddrFilter#test is not a valid filter for MTRoute

Can you please advise how can I make the route with SourceAddrFilter?

Thank you in advance

**Comment by raamtg** [comment] 2015-06-19 15:16
Can you show us your filter settings? You will have to add a source address
filter first, using *filter -a* if not already done so.

See here:
http://docs.jasminsms.com/en/latest/management/jcli/modules.html#filter-manager

Hope this helps...

**Comment by xamaxmacko** [comment] 2015-06-19 15:18
The filter is created.

Here are the settings of it : 

jcli : filter -s test
SourceAddrFilter:
source_addr = ^38095+

**Comment by zoufou** [comment] 2015-06-21 12:24
Confirmed issue, will be fixed in next release.

Please watch this issue to know when it will be closed.

**Comment by zoufou** [comment] 2015-06-21 12:29
@xamaxmacko i've double checked and sorry, it is not a bug ! it is a normal behaviour:

You are not allowed to route **MT** traffic based on source address, here's the filters you can use for MT routes:

    MTFILTERS = ['TransparentFilter', 'UserFilter', 'GroupFilter', 'DestinationAddrFilter', 
             'ShortMessageFilter', 'DateIntervalFilter', 'TimeIntervalFilter', 'EvalPyFilter']

And MO filters:

    MOFILTERS = ['TransparentFilter', 'ConnectorFilter', 'SourceAddrFilter', 'DestinationAddrFilter', 
             'ShortMessageFilter', 'DateIntervalFilter', 'TimeIntervalFilter', 'EvalPyFilter']

**Closed by zoufou** 2015-06-21 12:29 UTC
Labels: discussion

**Comment by zoufou** [comment] 2015-06-22 10:53
@xamaxmacko you can still use **EvalPyFilter** which offer you all you need.
