### ISSUE TITLE
Dlr is received before jasmin saving queue-msgid hash on redis

### ISSUE THREAD

**Issue by balsagoth** [jookies/jasmin#472] opened 2016-09-25 00:47 UTC
I was able to reproduce the problem setting sumbit_throughput to 1 and making 300 requests with concurrency 3.

```
$ grep -i "Got a DLR for an unknown message id" messages.log                                                                                                                              master [d157cec] untracked
./messages.log:2016-09-24 20:52:40 WARNING  26527 Got a DLR for an unknown message id: 142 (coded:142)
./messages.log:2016-09-24 20:52:45 WARNING  26527 Got a DLR for an unknown message id: 147 (coded:147)
./messages.log:2016-09-24 20:53:35 WARNING  26527 Got a DLR for an unknown message id: 196 (coded:196)
./messages.log:2016-09-24 20:54:10 WARNING  26527 Got a DLR for an unknown message id: 230 (coded:230)
```

On redis

```
redis:6379> keys dlr:*
1) "dlr:113809b0-9705-4966-829f-bdbf1abca59c"
2) "dlr:1e5de7e6-5e69-4549-87a1-33da2f95f9f9"
3) "dlr:02167e03-5c01-4a96-a6b1-3aac40e0bf96"
4) "dlr:015fbe3e-dc14-453b-94cc-49a449b8dbd9"
redis:6379> hget queue-msgid:142 msgid
"113809b0-9705-4966-829f-bdbf1abca59c"
redis:6379> hget queue-msgid:147 msgid
"02167e03-5c01-4a96-a6b1-3aac40e0bf96"
redis:6379> hget queue-msgid:196 msgid
"015fbe3e-dc14-453b-94cc-49a449b8dbd9"
redis:6379> hget queue-msgid:230 msgid
"1e5de7e6-5e69-4549-87a1-33da2f95f9f9"
redis:6379>

```

On redis.log you can see the problem:

```

> grep -ri "1e5de7e6-5e69-4549-87a1-33da2f95f9f9\|queue-msgid:230" redis-client.log                                                                                                      master [d157cec] untracked
redis-client.log:2016-09-24 20:53:01 DEBUG    26527 Executing redis command: ('HMSET', 'dlr:1e5de7e6-5e69-4549-87a1-33da2f95f9f9', 'sc', 'httpapi', 'url', 'http://127.0.0.1:5000/dlr', 'expiry', 86400, 'method', 'GET', 'level', 3)
redis-client.log:2016-09-24 20:53:01 DEBUG    26527 Executing redis command: ('EXPIRE', 'dlr:1e5de7e6-5e69-4549-87a1-33da2f95f9f9', 86400)
redis-client.log:2016-09-24 20:54:10 DEBUG    26527 Executing redis command: ('HGETALL', 'dlr:1e5de7e6-5e69-4549-87a1-33da2f95f9f9')
redis-client.log:2016-09-24 20:54:10 DEBUG    26527 Executing redis command: ('HGETALL', 'queue-msgid:230')
redis-client.log:2016-09-24 20:54:10 DEBUG    26527 Executing redis command: ('HMSET', 'queue-msgid:230', 'msgid', '1e5de7e6-5e69-4549-87a1-33da2f95f9f9', 'connector_type', 'httpapi')
redis-client.log:2016-09-24 20:54:10 DEBUG    26527 Executing redis command: ('EXPIRE', 'queue-msgid:230', 86400)
```

`hmset`  on [line 401](https://github.com/jookies/jasmin/blob/d157cec3e0ed325a8392d652245a2378e977cd2e/jasmin/managers/listeners.py#L401)  happens after `deliver_sm` with dlr is received.

**Comment by farirat** [comment] 2016-09-25 16:32
This is a confirmed issue, it happens that deliver_sm or data_sm holding dlr information is received before the msgid from submit_sm_resp get written to redis, the dlr is lost since no mapping is found.

This is a concurrency issue where writing to redis is slower than reading from it, this issue will be adressed in the current release (0.9)

**Comment by KumarDedhia** [comment] 2016-09-29 06:45
It seems that most of delay is caused due to pickling at this stage.
[line 252](https://github.com/jookies/jasmin/blob/d157cec3e0ed325a8392d652245a2378e977cd2e/jasmin/managers/listeners.py#L252) and that cant be avoided.

Is there any plan to switich to [msgpack](http://www.benfrederickson.com/dont-pickle-your-data/) handling non-objects(may be dict) as an alternative to pickling objects.

**Comment by farirat** [comment] 2016-09-29 12:33
Actual plan is to separate the processes to gain more performance, pickling cannot be avoided for the moment.

The dlr handling will be ported to a separate process with a retrial mechanism, both throwers (dlr and deliver) will be running in separate processes, this is the initial plan for 0.9 release and that's why it's still not final release.

**Comment by farirat** [comment] 2016-11-10 00:47
Work is in progress for this issue, closing it will take up to 3 to 5 releases where first one is just pushed now (0.9b13), a major design change is upcoming, here's the plan:

1. (Released in 0.9b13) the DLR throwers (http and smpp) will be running in standalone process, this will make some room for Jasmin to scale up while handling dlr throwing in a separate process (separate cpu core), as of **0.9b13** the jasmind will have it's internal dlr thrower disabled by default so users **MUST** run the new **jasmin-dlrd** daemon separately (systemd services are tight together: starting jasmind will automatically start jasmin-dlrd), getting back to old behaviour (internal monoprocess dlr throwing) is always possible using the **--enable-dlr-thrower** switch.
2. (Next release) The dlr map lookup will be done in a separate process as well, with a simple retrying mechanism to avoid not getting dlr map from redis because of possible latencies.
3. msgpack will be tested as an alternative to pickle, if performance is prooved then msgpack will replace pickle when possible, users will have the choice to switch between msgpack or pickle through configuration, will close #472 on this point.

BONUS: deliver_sm throwers (http and smpp) will also be handled in separate processes later on.

@balsagoth @KumarDedhia can you please test and measure performance of 0.9b13 compared to previous releases ? the dlr lookup issue is still there but with less frequency, it's going to be adressed in next release.

**Comment by farirat** [comment] 2016-11-22 23:17
0.9b15 is now released with a dlr map lookup standalone process, having a simple retrying mechanism to avoid not getting dlr map from redis because of possible latencies.

Next release: testing whether msgpack can be a replacement for cpickle.

**Comment by farirat** [comment] 2016-11-25 21:48
msgpack integration seems not possible for the moment, a lot of objects getting serialized using cpickle and this is not portable to msgpack.

**Closed by farirat** 2016-11-25 21:48 UTC
Labels: bug, critical, high prio, Tuning
