### ISSUE TITLE
TON change from smppccm interface does not take effect

### ISSUE THREAD

**Issue by cristianpetresimiononem** [jookies/jasmin#497] opened 2016-11-01 08:26 UTC
Steps:
- enter smppccm interface
- configure src_ton=0 for a specific connector
- persist
- restart connector
- generate an MT message from that connector + tcpdump => src ton=2 is sent within the submit_sm message, no matter what we configure for that connector in the smppccm interface

**Comment by farirat** [comment] 2016-11-01 21:53
Unable to reproduce the issue with Jasmin 0.9b12 (same as public 0.9b11 release), here are the details:

**Connector config:**
<img width="335" alt="1__telnet" src="https://cloud.githubusercontent.com/assets/1020111/19908796/19da8852-a085-11e6-8246-50c063985c59.png">

**Wireshark capture of a submitted sm:**
<img width="856" alt="capturing_from_vboxnet0" src="https://cloud.githubusercontent.com/assets/1020111/19908891/7b2d9e50-a085-11e6-9a89-04d650a5828d.png">

Notes:

- The submit_sm were pushed through Jasmin's http api,
- If you are pushing through smpp server then it is normal that Jasmin is keeping your original src_ton value, it will only update it to what you've set in smppccm when you're pushing through http api since there's no way to define src_ton in this api,
- If you need to update src_ton for messages you are pushing through smpp server then interception is your way to go.

**Comment by cristianpetresimiononem** [comment] 2016-11-02 07:23
Could you please repeat the above test with src_ton=0 ?

**Comment by farirat** [comment] 2016-11-02 12:08
hyg:
<img width="493" alt="capturing_from_vboxnet0" src="https://cloud.githubusercontent.com/assets/1020111/19928125/69ee5120-a0fd-11e6-8b94-10b6d7b2c8ad.png">

Closing this issue.

**Closed by farirat** 2016-11-02 12:08 UTC
Labels: bug, Support, unconfirmed
